# Generated by Django 5.0.7 on 2024-08-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_contactmodel_alter_experience_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='EndDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
